---
version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: gradle
    directory: /webapp
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directories: [/webapp, /schema]
    schedule:
      interval: weekly
